/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ApiAnswerType = {
    ITEM: 'ITEM',
    TEMPORAL: 'TEMPORAL',
    TEXT: 'TEXT'
} as const;
export type ApiAnswerType = typeof ApiAnswerType[keyof typeof ApiAnswerType];

