/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiAnswer } from './apiAnswer';
import { ApiVerdictStatus } from './apiVerdictStatus';


export interface ApiAnswerSet { 
    id: string;
    status: ApiVerdictStatus;
    taskId: string;
    answers: Array<ApiAnswer>;
}
export namespace ApiAnswerSet {
}


