/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiMediaItem } from './apiMediaItem';
import { TemporalRange } from './temporalRange';
import { ApiAnswerType } from './apiAnswerType';


export interface ApiAnswer { 
    type: ApiAnswerType;
    item?: ApiMediaItem;
    text?: string;
    start?: number;
    end?: number;
    temporalRange?: TemporalRange;
}
export namespace ApiAnswer {
}


