/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiClientAnswer { 
    text?: string | null;
    mediaItemName?: string | null;
    mediaItemCollectionName?: string | null;
    start?: number | null;
    end?: number | null;
}

