/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ApiContentType = {
    EMPTY: 'EMPTY',
    TEXT: 'TEXT',
    VIDEO: 'VIDEO',
    IMAGE: 'IMAGE'
} as const;
export type ApiContentType = typeof ApiContentType[keyof typeof ApiContentType];

