/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiContentType } from './apiContentType';


export interface ApiContentElement { 
    contentType: ApiContentType;
    content?: string;
    offset: number;
}
export namespace ApiContentElement {
}


