/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiTask } from './apiTask';
import { ApiEvaluationType } from './apiEvaluationType';
import { ApiEvaluationTemplate } from './apiEvaluationTemplate';


export interface ApiEvaluation { 
    evaluationId: string;
    name: string;
    type: ApiEvaluationType;
    template: ApiEvaluationTemplate;
    created: number;
    started?: number;
    ended?: number;
    tasks: Array<ApiTask>;
}
export namespace ApiEvaluation {
}


