/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ApiEvaluationType = {
    SYNCHRONOUS: 'SYNCHRONOUS',
    ASYNCHRONOUS: 'ASYNCHRONOUS',
    NON_INTERACTIVE: 'NON_INTERACTIVE'
} as const;
export type ApiEvaluationType = typeof ApiEvaluationType[keyof typeof ApiEvaluationType];

