/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RunManagerStatus } from './runManagerStatus';
import { ApiTeamTaskOverview } from './apiTeamTaskOverview';


export interface ApiEvaluationOverview { 
    state: RunManagerStatus;
    teamOverviews: Array<ApiTeamTaskOverview>;
}
export namespace ApiEvaluationOverview {
}


