/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiEvaluationTemplateOverview { 
    id: string;
    name: string;
    description?: string;
    taskCount: number;
    teamCount: number;
}

