/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiRunProperties } from './apiRunProperties';
import { ApiEvaluationType } from './apiEvaluationType';


export interface ApiEvaluationStartMessage { 
    templateId: string;
    name: string;
    type: ApiEvaluationType;
    properties: ApiRunProperties;
}
export namespace ApiEvaluationStartMessage {
}


