/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ApiHintOption = {
    IMAGE_ITEM: 'IMAGE_ITEM',
    VIDEO_ITEM_SEGMENT: 'VIDEO_ITEM_SEGMENT',
    TEXT: 'TEXT',
    EXTERNAL_IMAGE: 'EXTERNAL_IMAGE',
    EXTERNAL_VIDEO: 'EXTERNAL_VIDEO'
} as const;
export type ApiHintOption = typeof ApiHintOption[keyof typeof ApiHintOption];

