/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiTemporalRange } from './apiTemporalRange';
import { ApiMediaItem } from './apiMediaItem';
import { ApiHintType } from './apiHintType';


export interface ApiHint { 
    type: ApiHintType;
    start?: number;
    end?: number;
    description?: string;
    path?: string;
    dataType?: string;
    item?: ApiMediaItem;
    range?: ApiTemporalRange;
}
export namespace ApiHint {
}


