/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ApiMediaType = {
    IMAGE: 'IMAGE',
    VIDEO: 'VIDEO',
    TEXT: 'TEXT'
} as const;
export type ApiMediaType = typeof ApiMediaType[keyof typeof ApiMediaType];

