/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiMediaCollection { 
    id?: string;
    name: string;
    description?: string;
    basePath?: string;
    itemCount: number;
}

