/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiMediaItemMetaDataEntry } from './apiMediaItemMetaDataEntry';
import { ApiMediaType } from './apiMediaType';


export interface ApiMediaItem { 
    mediaItemId: string;
    name: string;
    type: ApiMediaType;
    collectionId: string;
    location: string;
    durationMs?: number;
    fps?: number;
    metadata: Array<ApiMediaItemMetaDataEntry>;
}
export namespace ApiMediaItem {
}


