/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ApiRole = {
    ANYONE: 'ANYONE',
    VIEWER: 'VIEWER',
    PARTICIPANT: 'PARTICIPANT',
    JUDGE: 'JUDGE',
    ADMIN: 'ADMIN'
} as const;
export type ApiRole = typeof ApiRole[keyof typeof ApiRole];

