/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiRunProperties { 
    participantCanView: boolean;
    shuffleTasks: boolean;
    allowRepeatedTasks: boolean;
    limitSubmissionPreviews: number;
}

