/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ApiScoreOption = {
    KIS: 'KIS',
    AVS: 'AVS',
    LEGACY_AVS: 'LEGACY_AVS'
} as const;
export type ApiScoreOption = typeof ApiScoreOption[keyof typeof ApiScoreOption];

