/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiAnswerSet } from './apiAnswerSet';


export interface ApiSubmission { 
    submissionId: string;
    teamId: string;
    memberId: string;
    teamName: string;
    memberName: string;
    timestamp: number;
    answers: Array<ApiAnswerSet>;
}

