/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiScore } from './apiScore';


export interface ApiScoreOverview { 
    name: string;
    taskGroup?: string;
    scores: Array<ApiScore>;
}

