/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiSubmission } from './apiSubmission';


export interface ApiSubmissionInfo { 
    evaluationId: string;
    taskId: string;
    submissions: Array<ApiSubmission>;
}

