/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiTemporalRange } from './apiTemporalRange';
import { ApiMediaItem } from './apiMediaItem';
import { ApiTargetType } from './apiTargetType';


export interface ApiTarget { 
    type: ApiTargetType;
    target?: string;
    range?: ApiTemporalRange;
    item?: ApiMediaItem;
}
export namespace ApiTarget {
}


