/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiTaskOverview } from './apiTaskOverview';


export interface ApiTeamTaskOverview { 
    teamId: string;
    tasks: Array<ApiTaskOverview>;
}

