/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiUser } from './apiUser';


export interface ApiTeam { 
    id?: string;
    name?: string;
    color?: string;
    users: Array<ApiUser>;
    logoData?: string;
    teamId: string;
}

