/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiTaskTemplateInfo { 
    templateId: string;
    name: string;
    comment?: string;
    taskGroup: string;
    taskType: string;
    duration: number;
}

