/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiTemporalUnit } from './apiTemporalUnit';


export interface ApiTemporalPoint { 
    value: string;
    unit: ApiTemporalUnit;
}
export namespace ApiTemporalPoint {
}


