/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ApiTeamAggregatorType = {
    MIN: 'MIN',
    MAX: 'MAX',
    MEAN: 'MEAN',
    LAST: 'LAST'
} as const;
export type ApiTeamAggregatorType = typeof ApiTeamAggregatorType[keyof typeof ApiTeamAggregatorType];

