/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ApiTemporalUnit = {
    FRAME_NUMBER: 'FRAME_NUMBER',
    SECONDS: 'SECONDS',
    MILLISECONDS: 'MILLISECONDS',
    TIMECODE: 'TIMECODE'
} as const;
export type ApiTemporalUnit = typeof ApiTemporalUnit[keyof typeof ApiTemporalUnit];

