/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ApiTaskOption = {
    HIDDEN_RESULTS: 'HIDDEN_RESULTS',
    MAP_TO_SEGMENT: 'MAP_TO_SEGMENT',
    PROLONG_ON_SUBMISSION: 'PROLONG_ON_SUBMISSION'
} as const;
export type ApiTaskOption = typeof ApiTaskOption[keyof typeof ApiTaskOption];

