/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiSubmission } from './apiSubmission';


export interface ApiTask { 
    taskId: string;
    templateId: string;
    started?: number;
    ended?: number;
    submissions: Array<ApiSubmission>;
}

