/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiHintOption } from './apiHintOption';
import { ApiTargetOption } from './apiTargetOption';
import { ApiSubmissionOption } from './apiSubmissionOption';
import { ApiTaskOption } from './apiTaskOption';
import { ApiScoreOption } from './apiScoreOption';


export interface ApiTaskType { 
    name: string;
    duration: number;
    targetOption: ApiTargetOption;
    hintOptions: Array<ApiHintOption>;
    submissionOptions: Array<ApiSubmissionOption>;
    taskOptions: Array<ApiTaskOption>;
    scoreOption: ApiScoreOption;
    configuration: { [key: string]: string; };
}
export namespace ApiTaskType {
}


