/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ApiTaskStatus = {
    NO_TASK: 'NO_TASK',
    CREATED: 'CREATED',
    PREPARING: 'PREPARING',
    RUNNING: 'RUNNING',
    ENDED: 'ENDED',
    IGNORED: 'IGNORED'
} as const;
export type ApiTaskStatus = typeof ApiTaskStatus[keyof typeof ApiTaskStatus];

