/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ApiTargetType = {
    JUDGEMENT: 'JUDGEMENT',
    JUDGEMENT_WITH_VOTE: 'JUDGEMENT_WITH_VOTE',
    MEDIA_ITEM: 'MEDIA_ITEM',
    MEDIA_ITEM_TEMPORAL_RANGE: 'MEDIA_ITEM_TEMPORAL_RANGE',
    TEXT: 'TEXT'
} as const;
export type ApiTargetType = typeof ApiTargetType[keyof typeof ApiTargetType];

