/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiTemporalPoint } from './apiTemporalPoint';


export interface ApiTemporalRange { 
    start: ApiTemporalPoint;
    end: ApiTemporalPoint;
}

