/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ApiTargetOption = {
    SINGLE_MEDIA_ITEM: 'SINGLE_MEDIA_ITEM',
    SINGLE_MEDIA_SEGMENT: 'SINGLE_MEDIA_SEGMENT',
    JUDGEMENT: 'JUDGEMENT',
    VOTE: 'VOTE',
    TEXT: 'TEXT'
} as const;
export type ApiTargetOption = typeof ApiTargetOption[keyof typeof ApiTargetOption];

