/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiRole } from './apiRole';


export interface ApiUserRequest { 
    username: string;
    password?: string;
    role?: ApiRole;
}
export namespace ApiUserRequest {
}


