/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiRole } from './apiRole';


export interface ApiUser { 
    id?: string;
    username?: string;
    role?: ApiRole;
    sessionId?: string;
}
export namespace ApiUser {
}


