/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ApiVerdictStatus = {
    CORRECT: 'CORRECT',
    WRONG: 'WRONG',
    INDETERMINATE: 'INDETERMINATE',
    UNDECIDABLE: 'UNDECIDABLE'
} as const;
export type ApiVerdictStatus = typeof ApiVerdictStatus[keyof typeof ApiVerdictStatus];

