/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiVerdictStatus } from './apiVerdictStatus';


export interface ApiVote { 
    verdict: ApiVerdictStatus;
}
export namespace ApiVote {
}


