/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QueryEvent } from './queryEvent';


export interface QueryEventLog { 
    timestamp: number;
    events: Array<QueryEvent>;
}

