/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const QueryEventCategory = {
    TEXT: 'TEXT',
    IMAGE: 'IMAGE',
    SKETCH: 'SKETCH',
    FILTER: 'FILTER',
    BROWSING: 'BROWSING',
    COOPERATION: 'COOPERATION',
    OTHER: 'OTHER'
} as const;
export type QueryEventCategory = typeof QueryEventCategory[keyof typeof QueryEventCategory];

