/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QueryEventCategory } from './queryEventCategory';


export interface QueryEvent { 
    timestamp: number;
    category: QueryEventCategory;
    type: string;
    value: string;
}
export namespace QueryEvent {
}


