/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiClientAnswer } from './apiClientAnswer';


export interface RankedAnswer { 
    answer: ApiClientAnswer;
    rank?: number;
}

