/**
 * DRES Client API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const RunManagerStatus = {
    CREATED: 'CREATED',
    ACTIVE: 'ACTIVE',
    TERMINATED: 'TERMINATED'
} as const;
export type RunManagerStatus = typeof RunManagerStatus[keyof typeof RunManagerStatus];

